{{- if and .Values.ingress.enabled .Values.ingress.stripPrefix }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-stripprefix" (include "face-api.fullname" .) }}
  labels:
    {{- include "face-api.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.stripPrefix | quote }}
{{- end }}